/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.simulator;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Admin
 */
public class WelcomeGUI extends javax.swing.JFrame {
    private JMenuBar menuBar;
    private JMenu fileMenu, waiterMenu, menuMenu, configMenu;
    private JMenuItem loadLicenseItem, loadWaiterDataItem, loadMenuOfDayItem, generalConfigItem;
    private JTextArea informationArea;
    private JButton startButton;

    /**
     * Creates new form WelcomeGUI
     */
    public WelcomeGUI() {
        initComponents();
        setTitle("Welcome to Restaurant Simulator");
        setSize(600, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        menuBar = new JMenuBar();
        fileMenu = new JMenu("File");
        waiterMenu = new JMenu("Waiter");
        menuMenu = new JMenu("Menu");
        configMenu = new JMenu("Config");
        
        loadLicenseItem = new JMenuItem("Load License File");
        loadWaiterDataItem = new JMenuItem("Load/Add Waiter Data");
        loadMenuOfDayItem = new JMenuItem("Load Menu of the Day");
        generalConfigItem = new JMenuItem("General Configuration");
        
        fileMenu.add(loadLicenseItem);
        waiterMenu.add(loadWaiterDataItem);
        menuMenu.add(loadMenuOfDayItem);
        configMenu.add(generalConfigItem);
        
        menuBar.add(fileMenu);
        menuBar.add(waiterMenu);
        menuBar.add(menuMenu);
        menuBar.add(configMenu);
        setJMenuBar(menuBar);
        
        informationArea = new JTextArea();
        informationArea.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(informationArea);
        
        startButton = new JButton("Start");
        startButton.setEnabled(false);
        
        Container container = getContentPane();
        container.setLayout(new BorderLayout());
        container.add(scrollPane, BorderLayout.CENTER);
        container.add(startButton, BorderLayout.SOUTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
